### ISSUE TITLE
Compilation problem after upgrade from 4.3.1. to 4.4.0

### ISSUE THREAD

**Issue by krzcho** [fullcalendar/fullcalendar-angular#280]
```
ERROR in ../node_modules/@fullcalendar/angular/node_modules/@fullcalendar/core/main.d.ts:5:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: version, OptionsI
nput, EventInput, EventDef, EventDefHash, EventInstance, EventInstanceHash, parseEventDef, createEventInstance, EventTuple, BusinessHoursInput, parseBusinessHours, applyAll, debounce, padStart, isInt, cap
italiseFirstLetter, parseFieldSpecs, compareByFieldSpecs, compareByFieldSpec, flexibleCompare, computeVisibleDayRange, refineProps, matchCellWidths, uncompensateScroll, compensateScroll, subtractInnerElHe
ight, isMultiDayRange, distributeHeight, undistributeHeight, preventSelection, allowSelection, preventContextMenu, allowContextMenu, compareNumbers, enableCursor, disableCursor, diffDates, htmlEscape, css
ToStr, removeExact, isArraysEqual, memoize, memoizeOutput, memoizeRendering, MemoizedRendering, intersectRects, Rect, pointInsideRect, constrainPoint, getRectCenter, diffPoints, Point, translateRect, mapH
ash, filterHash, isPropsEqual, findElements, findChildren, htmlToElement, createElement, insertAfterElement, prependToElement, removeElement, appendToElement, applyStyle, applyStyleProp, elementMatches, e
lementClosest, forceClassName, EventStore, filterEventStoreDefs, createEmptyEventStore, mergeEventStores, getRelevantEvents, eventTupleToStore, EventUiHash, EventUi, processScopedUiProps, combineEventUis,
 Splitter, SplittableProps, buildGotoAnchorHtml, getAllDayHtml, getDayClasses, preventDefault, listenBySelector, whenTransitionDone, computeInnerRect, computeEdges, computeHeightAndMargins, getClippingPar
ents, computeClippingRect, computeRect, unpromisify, EmitterMixin, EmitterInterface, DateRange, rangeContainsMarker, intersectRanges, rangesEqual, rangesIntersect, rangeContainsRange, Mixin, PositionCache
, ScrollComponent, ScrollbarWidths, ScrollController, ElementScrollController, WindowScrollController, Theme, Component, ComponentContext, DateComponent, Seg, EventSegUiInteractionState, Calendar, DatePoi
ntTransform, DateSpanTransform, DateSelectionApi, View, ViewProps, FgEventRenderer, buildSegCompareObj, FillRenderer, DateProfileGenerator, DateProfile, ViewDef, ViewSpec, DateSpan, DateSpanApi, DatePoint
Api, isDateSpansEqual, DateMarker, addDays, startOfDay, addMs, addWeeks, diffWeeks, diffWholeWeeks, diffWholeDays, diffDayAndTime, diffDays, isValidDate, Duration, createDuration, isSingleDay, multiplyDur
ation, addDurations, asRoughMinutes, asRoughSeconds, asRoughMs, wholeDivideDurations, greatestDurationDenominator, DateEnv, DateMarkerMeta, DateFormatter, createFormatter, VerboseFormattingArg, formatIsoT
imeString, NamedTimeZoneImpl, parseMarker, EventSourceDef, EventSource, EventSourceHash, Interaction, InteractionSettings, interactionSettingsToStore, interactionSettingsStore, InteractionSettingsStore, P
ointerDragEvent, Hit, dateSelectionJoinTransformer, eventDragMutationMassager, EventDropTransformers, EventResizeJoinTransforms, ElementDragging, formatDate, formatRange, globalDefaults, config, Recurring
Type, ParsedRecurring, DragMetaInput, DragMeta, parseDragMeta, createPlugin, PluginDef, PluginDefInput, ViewPropsTransformer, ViewContainerModifier, reducerFunc, Action, CalendarState, CalendarComponentPr
ops, DayHeader, computeFallbackHeaderFormat, renderDateCell, DaySeries, EventInteractionState, EventRenderRange, sliceEventStore, hasBgRendering, getElSeg, DayTable, DayTableSeg, DayTableCell, Slicer, Sli
cedProps, EventMutation, applyMutationToEventStore, Constraint, ConstraintInput, AllowFunc, isPropsValid, isInteractionValid, EventApi, requestJson, EventHandlerName, EventHandlerArgs, EventHandlerArg, Ev
entRenderingChoice, NON_DATE_PROPS, DATE_PROPS, eventDefParserFunc, GenericHash, ClassNameInput, ElementContent, UNSCOPED_EVENT_UI_PROPS, default, ThemeClass, EqualityFuncHash, DateComponentHash, Calendar
Interaction, CalendarInteractionClass, OptionChangeHandler, OptionChangeHandlerMap, ViewDefHash, ViewSpecHash, DAY_IDS, DurationInput, DateInput, FormatterInput, NamedTimeZoneImplClass, EventSourceError, 
EventInputTransformer, EventSourceSuccessResponseHandler, EventSourceErrorResponseHandler, EventSourceInput, EventSourceFetcher, InteractionClass, eventIsDraggableTransformer, ElementDraggingClass, rtlDef
aults, ViewPropsTransformerClass, PluginSystem, CalendarComponent, eventDefMutationApplier, OverlapFunc, isPropsValidTester, LocaleCodeArg, LocaleSingularArg, RawLocaleMap, OptionsManager, EventSourceApi,
 ViewClass, ViewConfigInput, ViewConfigInputHash, ViewConfigHash, CmdFormatterFunc, CmdFormatter, FuncFormatterFunc, FuncFormatter, EventSourceFunc, _default, ExternalDefTransform, Toolbar                
                                                                                                                                                                                                            
5 declare module '@fullcalendar/core' {                                                                                                                                                                     
  ~~~~~~~                                                                                                                                                                                                   
                                                                                                                                                                                                            
  ../node_modules/@fullcalendar/core/main.d.ts:5:1                                                                                                                                                          
    5 declare module '@fullcalendar/core' {                                                                                                                                                                 
      ~~~~~~~                                                                                                                                                                                               
    Conflicts are in this file.                                                                                                                                                                             
../node_modules/@fullcalendar/angular/node_modules/@fullcalendar/core/main.d.ts:970:9 - error TS2687: All declarations of 'view' must have identical modifiers.                                             

...

```

any ideas? it looks like definition duplication from two locations (@fullcalendar/core and @fullcalendar/angular/node_modules/@fullcalendar/core)

**Comment by TristanBenschop** [comment]
Can you check your package-lock.json. Does it contain a dependency to @fullcalenar/core under the @fullcalendar/angular definition which is "resolved" to version 4.3.1 instead of 4.4.0?

Seems like the 4.4.0 version got shipped with a wrong dependency.

https://github.com/fullcalendar/fullcalendar-angular/blob/v4.4.0/projects/fullcalendar/package.json

**Comment by krzcho** [comment]
Yes, I confirm that

   ```
 "@fullcalendar/angular": {
      "version": "4.4.0",
      "resolved": "https://registry.npmjs.org/@fullcalendar/angular/-/angular-4.4.0.tgz",
      "integrity": "sha512-GVk88gpDeTknDKkeu8kP6b7gWHQ8R+NZqZmaFY5yoJTorDZ0gLr9cYaxys+InvFVatHWb12aLB7UpNxFAfLHKg==",
      "requires": {
        "@fullcalendar/core": "~4.3.1",
        "fast-deep-equal": "^2.0.1",
        "tslib": "^1.9.0"
      },
      "dependencies": {
        "@fullcalendar/core": {
          "version": "4.3.1",
          "resolved": "https://registry.npmjs.org/@fullcalendar/core/-/core-4.3.1.tgz",
          "integrity": "sha512-Eh+p/wpMkWGu26f8NpfQK9ecQMoZxX/aopv+0+4/CH+Ip0paP6iEc40JYgTz7RFl0bFqV1dvwyGyUZ4+9ZeySA=="
        }
      }
    },
```

**Comment by pwilkowski** [comment]
Yes I have the same problem, fix please, so far quick workaround is to delete manually folder:
`node_modules/@fullcalendar/angular/node_modules`

**Comment by irustm** [comment]
@krzcho Please show me yours. 
`npm ls @fullcalendar/core`

**Comment by mtinnes** [comment]
@pwilkowski deleting the folder did not work for me.

@irustm Here's mine (not that you asked)

```
npm ls @fullcalendar/core
+-- @fullcalendar/angular@4.4.0
| `-- @fullcalendar/core@4.3.1
`-- @fullcalendar/core@4.4.0
```

**Comment by irustm** [comment]
@mtinnes thanks!

**Comment by arshaw** [comment]
this is fixed in v4.4.1

sorry about that
