### ISSUE TITLE
Angular 9 update

### ISSUE THREAD

**Issue by chiragatlas** [fullcalendar/fullcalendar-angular#291]
I am trying to update my application to Angular 9, But it is showing below error
I already set fullcalendar/angular to 4.4.5 beta
here is my full package.json file

`{
  "name": "genius-app",
  "version": "1.3.0",
  "repository": {
    "type": "git",
    "url": "git+https://chiragmodi14@bitbucket.org/aswwordpress/genius-planner-app.git"
  },
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "nodemon": "",
    "start:server": "nodemon ./node/app.js"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^9.0.1",
    "@angular/cdk": "^9.0.0",
    "@angular/common": "^9.0.1",
    "@angular/compiler": "^9.0.1",
    "@angular/core": "^9.0.1",
    "@angular/forms": "~9.0.1",
    "@angular/material": "^9.0.0",
    "@angular/material-moment-adapter": "^9.0.0",
    "@angular/platform-browser": "^9.0.1",
    "@angular/platform-browser-dynamic": "^9.0.1",
    "@angular/router": "^9.0.1",
    "@fullcalendar/angular": "^4.4.5-beta",
    "@fullcalendar/core": "^4.4.0",
    "@fullcalendar/daygrid": "^4.4.0",
    "@fullcalendar/interaction": "^4.4.0",
    "@fullcalendar/list": "^4.4.0",
    "@fullcalendar/timegrid": "^4.4.0",
    "angular": "^1.7.9",
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.19.0",
    "chart.js": "^2.9.3",
    "classlist.js": "^1.1.20150312",
    "cookieconsent": "^3.1.1",
    "core-js": "^2.6.11",
    "country-list-js": "^3.1.5",
    "ejs": "^2.7.4",
    "email-templates": "^6.1.1",
    "express": "^4.17.1",
    "ical-generator": "^1.9.2",
    "jsonwebtoken": "^8.5.1",
    "mailchimp-api-v3": "^1.13.1",
    "multer": "^1.4.2",
    "mysql2": "^1.7.0",
    "ng-recaptcha": "^5.0.0",
    "ng2-charts": "^2.3.0",
    "ngx-color-picker": "^7.5.0",
    "ngx-cookieconsent": "^2.2.3",
    "ngx-image-cropper": "^3.0.3",
    "ngx-material-timepicker": "^5.3.0",
    "node-cron": "^2.0.3",
    "nodemailer": "^6.4.2",
    "rxjs": "^6.5.4",
    "sequelize": "^5.21.4",
    "stripe": "^7.15.0",
    "tslib": "^1.10.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.2",
    "@angular/cli": "^9.0.2",
    "@angular/compiler-cli": "^9.0.1",
    "@angular/language-service": "^9.0.1",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.1.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ngx-scrollbar": "^7.2.0",
    "nodemon": "^1.19.4",
    "protractor": "^5.4.3",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.7.5"
  }
}
`
![image](https://user-images.githubusercontent.com/31877988/76527110-aededd00-6494-11ea-9d02-a3d1394628a8.png)

**Comment by chiragatlas** [comment]
I have forced update this, but drag and drop in calendar not working.

**Comment by gitalvininfo** [comment]
any updates ? did you implement it in Angular 9 ? Can you provide your code in stackblitz? 

Thanks.

**Comment by dawa-liverpudlian** [comment]
is fullcalendar compatible with angular 9 ??

**Comment by Timebutt** [comment]
@dawa-liverpudlian I was running `4.4.5-beta`  in my Angular 9 project without issues. The newer `5.0.0-beta.2` only supports Angular 9.

**Comment by dawa-liverpudlian** [comment]
@Timebutt Thank you for the response. Will try it out.

**Comment by AnassL** [comment]
I've tried successfully an angular 9.1.4 app with the following packages:
        "@fullcalendar/angular": "4.4.5-beta",
        "@fullcalendar/core": "4.4.0",
        "@fullcalendar/daygrid": "4.4.0",
        "@fullcalendar/interaction": "4.4.0",
        "@fullcalendar/list": "4.4.0",
        "@fullcalendar/moment": "4.4.0",
        "@fullcalendar/rrule": "4.4.0",
        "@fullcalendar/timegrid": "4.4.0",

But the weird thing is when upgraded to 9.1.9, none of 5.0.0 beta versions worked even 5.0.0-beta2 as suggested above didn't work. I keep getting the following error:

**ERROR** in src/app/calendar/calendar.component.ts:890:31 - error TS2339: **Property 'rerenderEvents' does not exist on type 'Calendar'**.

`890         this._fullCalendarApi.rerenderEvents();`

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo.

I tested the v4 angular debug template and after doing "update all deps to latest", I get fullcalendar 4.4.2 and angular 9.1.9 with no issues:

https://stackblitz.com/edit/github-avymb2

So it seems like that resolved the original issue, otherwise please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) or steps to reproduce the issue.

The current v4 release is 4.4.2 but there was a beta 4.4.5 release a few months ago so I believe that is causing some confusion because of the higher version number.

**Comment by AnassL** [comment]
Thanks for your reply @acerix, after ensured that all deps are latest I've tried 4.4.2 with angular 9.1.9 but got now the following error:

ERROR in The target entry-point "@fullcalendar/angular" has missing dependencies:
 - @fullcalendar/core/types/input-types
 - @fullcalendar/core/datelib/env
 - @fullcalendar/core/datelib/duration
 - @fullcalendar/core/datelib/formatting
 - @fullcalendar/core/datelib/date-range
 - @fullcalendar/core/datelib/locale
 - @fullcalendar/core/validation
 - @fullcalendar/core/structs/event-source

Any idea why this happens ?

**Comment by AnassL** [comment]
Sorry, found my mistake, I used a shared module that was bringing in some conflicting stuff, as soon as removed it, I got it to work without any compiling error using angular 9.1.9 and the following packages:

"@fullcalendar/angular": "4.4.5-beta",
"@fullcalendar/core": "4.4.2",
"@fullcalendar/daygrid": "4.4.2",
"@fullcalendar/interaction": "4.4.2",
"@fullcalendar/list": "4.4.2",
"@fullcalendar/moment": "4.4.2",
"@fullcalendar/rrule": "4.4.2",
"@fullcalendar/timegrid": "4.4.2",

**Comment by blackholegalaxy** [comment]
It doesn't work on our side. We still have the error 
```
ERROR in The target entry-point "@fullcalendar/angular" has missing dependencies:
 - @fullcalendar/core/types/input-types
 - @fullcalendar/core/datelib/env
 - @fullcalendar/core/datelib/duration
 - @fullcalendar/core/datelib/formatting
 - @fullcalendar/core/datelib/date-range
 - @fullcalendar/core/datelib/locale
 - @fullcalendar/core/validation
 - @fullcalendar/core/structs/event-source
```

when running a `ng serve` after a `yarn install`. We use all packages at version 4.4.2 and angular is 9.1.9.

```
    "@fullcalendar/angular": "4.4.2",
    "@fullcalendar/core": "4.4.2",
    "@fullcalendar/daygrid": "4.4.2",
    "@fullcalendar/interaction": "4.4.2",
    "@fullcalendar/list": "4.4.2",
    "@fullcalendar/moment": "4.4.2",
    "@fullcalendar/timegrid": "4.4.2",
```

I think on Stackblitz Ivy may not be enabled and so it doesn't run into the build problem.
