### PR TITLE
Update depends @fullcalendar/core

### LINKED ISSUE #280: Compilation problem after upgrade from 4.3.1. to 4.4.0
```
ERROR in ../node_modules/@fullcalendar/angular/node_modules/@fullcalendar/core/main.d.ts:5:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: version, OptionsI
nput, EventInput, EventDef, EventDefHash, EventInstance, EventInstanceHash, parseEventDef, createEventInstance, EventTuple, BusinessHoursInput, parseBusinessHours, applyAll, debounce, padStart, isInt, cap
italiseFirstLetter, parseFieldSpecs, compareByFieldSpecs, compareByFieldSpec, flexibleCompare, computeVisibleDayRange, refineProps, matchCellWidths, uncompensateScroll, compensateScroll, subtractInnerElHe
ight, isMultiDayRange, distributeHeight, undistributeHeight, preventSelection, allowSelection, preventContextMenu, allowContextMenu, compareNumbers, enableCursor, disableCursor, diffDates, htmlEscape, css
ToStr, removeExact, isArraysEqual, memoize, memoizeOutput, memoizeRendering, MemoizedRendering, intersectRects, Rect, pointInsideRect, constrainPoint, getRectCenter, diffPoints, Point, translateRect, mapH
ash, filterHash, isPropsEqual, findElements, findChildren, htmlToElement, createElement, insertAfterElement, prependToElement, removeElement, appendToElement, applyStyle, applyStyleProp, elementMatches, e
lementClosest, forceClassName, EventStore, filterEventStoreDefs, createEmptyEventStore, mergeEventStores, getRelevantEvents, eventTupleToStore, EventUiHash, EventUi, processScopedUiProps, combineEventUis,
 Splitter, SplittableProps, buildGotoAnchorHtml, getAllDayHtml, getDayClasses, preventDefault, listenBySelector, whenTransitionDone, computeInnerRect, computeEdges, computeHeightAndMargins, getClippingPar
ents, computeClippingRect, computeRect, unpromisify, EmitterMixin, EmitterInterface, DateRange, rangeContainsMarker, intersectRanges, rangesEqual, rangesIntersect, rangeContainsRange, Mixin, PositionCache
, ScrollComponent, ScrollbarWidths, ScrollController, ElementScrollController, WindowScrollController, Theme, Component, ComponentContext, DateComponent, Seg, EventSegUiInteractionState, Calendar, DatePoi
ntTransform, DateSpanTransform, DateSelectionApi, View, ViewProps, FgEventRenderer, buildSegCompareObj, FillRenderer, DateProfileGenerator, DateProfile, ViewDef, ViewSpec, DateSpan, DateSpanApi, DatePoint
Api, isDateSpansEqual, DateMarker, addDays, startOfDay, addMs, addWeeks, diffWeeks, diffWholeWeeks, diffWholeDays, diffDayAndTime, diffDays, isValidDate, Duration, createDuration, isSingleDay, multiplyDur
ation, addDurations, asRoughMinutes, asRoughSeconds, asRoughMs, wholeDivideDurations, greatestDurationDenominator, DateEnv, DateMarkerMeta, DateFormatter, createFormatter, VerboseFormattingArg, formatIsoT
imeString, NamedTimeZoneImpl, parseMarker, EventSourceDef, EventSource, EventSourceHash, Interaction, InteractionSettings, interactionSettingsToStore, interactionSettingsStore, InteractionSettingsStore, P
ointerDragEvent, Hit, dateSelectionJoinTransformer, eventDragMutationMassager, EventDropTransformers, EventResizeJoinTransforms, ElementDragging, formatDate, formatRange, globalDefaults, config, Recurring
Type, ParsedRecurring, DragMetaInput, DragMeta, parseDragMeta, createPlugin, PluginDef, PluginDefInput, ViewPropsTransformer, ViewContainerModifier, reducerFunc, Action, CalendarState, CalendarComponentPr
ops, DayHeader, computeFallbackHeaderFormat, renderDateCell, DaySeries, EventInteractionState, EventRenderRange, sliceEventStore, hasBgRendering, getElSeg, DayTable, DayTableSeg, DayTableCell, Slicer, Sli
cedProps, EventMutation, applyMutationToEventStore, Constraint, ConstraintInput, AllowFunc, isPropsValid, isInteractionValid, EventApi, requestJson, EventHandlerName, EventHandlerArgs, EventHandlerArg, Ev
entRenderingChoice, NON_DATE_PROPS, DATE_PROPS, eventDefParserFunc, GenericHash, ClassNameInput, ElementContent, UNSCOPED_EVENT_UI_PROPS, default, ThemeClass, EqualityFuncHash, DateComponentHash, Calendar
Interaction, CalendarInteractionClass, OptionChangeHandler, OptionChangeHandlerMap, ViewDefHash, ViewSpecHash, DAY_IDS, DurationInput, DateInput, FormatterInput, NamedTimeZoneImplClass, EventSourceError, 
EventInputTransformer, EventSourceSuccessResponseHandler, EventSourceErrorResponseHandler, EventSourceInput, EventSourceFetcher, InteractionClass, eventIsDraggableTransformer, ElementDraggingClass, rtlDef
aults, ViewPropsTransformerClass, PluginSystem, CalendarComponent, eventDefMutationApplier, OverlapFunc, isPropsValidTester, LocaleCodeArg, LocaleSingularArg, RawLocaleMap, OptionsManager, EventSourceApi,
 ViewClass, ViewConfigInput, ViewConfigInputHash, ViewConfigHash, CmdFormatterFunc, CmdFormatter, FuncFormatterFunc, FuncFormatter, EventSourceFunc, _default, ExternalDefTransform, Toolbar                
                                                                                                                                                                                                            
5 declare module '@fullcalendar/core' {                                                                                                                                                                     
  ~~~~~~~                                                                                                                                                                                                   
                                                                                                                                                                                                            
  ../node_modules/@fullcalendar/core/main.d.ts:5:1                                                                                                                                                          
    5 declare module '@fullcalendar/core' {                                                                                                                                                                 
      ~~~~~~~                                                                                                                                                                                               
    Conflicts are in this file.                                                                                                                                                                             
../node_modules/@fullcalendar/angular/node_modules/@fullcalendar/core/main.d.ts:970:9 - error TS2687: All declarations of 'view' must have identical modifiers.                                             

...

```

any ideas? it looks like definition duplication from two locations (@fullcalendar/core and @fullcalendar/angular/node_modules/@fullcalendar/core)

### PR DESCRIPTION
**Pull request by irustm**
closes #280

### CODE REVIEW

**Comment by arshaw** [comment]
sorry about this. i'll get this done tonight. i'll also make a script that will prevent this from happening again in the future....

**Comment by arshaw** [comment]
i used a different solution to solve this
